// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9X58Ersi78bWmCqZl-p6Sd_5X2teDlj8',
    appId: '1:400468508566:web:a54b2bfb93ed89ed6ba7b7',
    messagingSenderId: '400468508566',
    projectId: 'new-bright-minds',
    authDomain: 'new-bright-minds.firebaseapp.com',
    storageBucket: 'new-bright-minds.firebasestorage.app',
    measurementId: 'G-HPSMS4L291',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0LSMU4osLJFnv9rrDxmZWkyEHIUVCKgM',
    appId: '1:400468508566:android:4fb780b97c16fb6d6ba7b7',
    messagingSenderId: '400468508566',
    projectId: 'new-bright-minds',
    storageBucket: 'new-bright-minds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaD88iF5EeI354xHLLfJwE6uX7Qm0P5Xo',
    appId: '1:400468508566:ios:bdbcaad678a20cb36ba7b7',
    messagingSenderId: '400468508566',
    projectId: 'new-bright-minds',
    storageBucket: 'new-bright-minds.firebasestorage.app',
    iosBundleId: 'com.example.newBrightMinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaD88iF5EeI354xHLLfJwE6uX7Qm0P5Xo',
    appId: '1:400468508566:ios:bdbcaad678a20cb36ba7b7',
    messagingSenderId: '400468508566',
    projectId: 'new-bright-minds',
    storageBucket: 'new-bright-minds.firebasestorage.app',
    iosBundleId: 'com.example.newBrightMinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9X58Ersi78bWmCqZl-p6Sd_5X2teDlj8',
    appId: '1:400468508566:web:6ba2701c85f667d96ba7b7',
    messagingSenderId: '400468508566',
    projectId: 'new-bright-minds',
    authDomain: 'new-bright-minds.firebaseapp.com',
    storageBucket: 'new-bright-minds.firebasestorage.app',
    measurementId: 'G-M9NZD9CC0S',
  );
}
